/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxStm.h"

#include "IfxPort.h"
#include "IfxPort_PinMap.h"
#include "Platform_Types.h"
#include "IfxPort_reg.h"

#include "Platform_Types.h"
#include "IfxI2c_I2c.h"
#include "IfxStm.h"

#include "vl53l0x_api.h"

void VL53L0X_I2C_Init(void);
int VL53L0X_Setup(void);
int VL53L0X_GetDistance(void);

IfxCpu_syncEvent cpuSyncEvent = 0;


/* ── 전역 변수 ── */
VL53L0X_Dev_t  g_tofDev;           /* 디바이스 구조체 */
VL53L0X_DEV    Dev = &g_tofDev;    /* 포인터 */
volatile int stttt;
volatile uint16_t dist;

void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);

    IfxPort_setPinModeOutput(IfxPort_P10_2.port, IfxPort_P10_2.pinIndex,
                                 IfxPort_OutputMode_pushPull,
                                 IfxPort_OutputIdx_general);

    IfxPort_setPinHigh(IfxPort_P10_2.port, IfxPort_P10_2.pinIndex);


    VL53L0X_I2C_Init();
    stttt = VL53L0X_Setup();

    while(1)
    {
        dist = VL53L0X_GetDistance();
        if(dist > 0x0044) IfxPort_setPinHigh(IfxPort_P10_2.port, IfxPort_P10_2.pinIndex);
        else IfxPort_setPinLow(IfxPort_P10_2.port, IfxPort_P10_2.pinIndex);
    }
}

int VL53L0X_Setup(void)
{
    VL53L0X_Error status;
    uint32_t refSpadCount;
    uint8_t  isApertureSpads;
    uint8_t  VhvSettings;
    uint8_t  PhaseCal;

    /* ① 디바이스 주소 설정 */
    Dev->I2cDevAddr = 0x29;       /* 7비트 주소 (고정) */
    Dev->comms_type = 1;          /* I2C */
    Dev->comms_speed_khz = 100;

    /* ② DataInit - 내부 구조체 초기화 */
    status = VL53L0X_DataInit(Dev);
    if (status) return -2;

    /* ③ StaticInit - NVM에서 설정 로드 */
    status = VL53L0X_StaticInit(Dev);
    if (status) return -3;

    /* ④ SPAD 캘리브레이션 (필수) */
    status = VL53L0X_PerformRefSpadManagement(Dev,
                &refSpadCount, &isApertureSpads);
    if (status) return -4;

    /* ⑤ Ref 캘리브레이션 (필수) */
    status = VL53L0X_PerformRefCalibration(Dev,
                &VhvSettings, &PhaseCal);
    if (status) return -5;

    /* ⑥ 싱글 측정 모드 설정 */
    status = VL53L0X_SetDeviceMode(Dev,
                VL53L0X_DEVICEMODE_SINGLE_RANGING);
    if (status) return -6;

    return 0;  /* 성공 */
}

int VL53L0X_GetDistance(void)
{
    VL53L0X_Error status;
    VL53L0X_RangingMeasurementData_t data;

    status = VL53L0X_PerformSingleRangingMeasurement(Dev, &data);

    if (status != VL53L0X_ERROR_NONE)
        return -1;

    /* RangeStatus == 0 이면 유효한 측정 */
    if (data.RangeStatus == 0)
        return data.RangeMilliMeter;    /* mm 단위 거리 */
    else
        return -2;  /* 범위 초과 또는 에러 */
}
