/**********************************************************************************************************************
 * \file sensor_data.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
#ifndef APP_SENSOR_DATA_H_
#define APP_SENSOR_DATA_H_

#include "Ifx_Types.h"
#include "FreeRTOS.h"
#include "semphr.h"

/* ── 상태 열거형 ── */
typedef enum { DRIVER_SEATED, DRIVER_ABSENT, DRIVER_UNCERTAIN } DriverState;
typedef enum { GEAR_P, GEAR_R, GEAR_N, GEAR_D, GEAR_ERROR }    GearState;
typedef enum { DOOR_OPEN, DOOR_CLOSE }                          DoorState;
typedef enum { MOTION_STOPPED, MOTION_MOVING }                  MotionState;

typedef enum {
    RISK_NORMAL,
    RISK_WARN_LV1,
    RISK_WARN_LV2,
    RISK_D_BRAKE,
    RISK_R_BRAKE,
    RISK_ROLLAWAY_WARN,
    RISK_ROLLAWAY_BRAKE,
    RISK_BRAKE_HOLD,
    RISK_RELEASE_WAIT
} RiskLevel;

/* ── 센서 데이터 (Task_Sensor가 채움, Task_Judge가 읽음) ── */
typedef struct {
    DriverState driver;
    GearState   gear;
    DoorState   door;
    float      speed_kmh;
    MotionState motion;
} SensorData;

/* ── 제어 명령 (Task_Judge가 채움, Task_CAN_TX가 읽음) ── */
typedef struct {
    RiskLevel   risk_level;
    uint8       brake_cmd;       /* 0=OFF, 1=ON, 2=HOLD */
    uint8       motor_mode;      /* 0=STOP, 1=FWD, 2=REV, 3=NEUTRAL, 4=PARK */
    uint8       buzzer_mode;     /* 0=OFF, 1=단속, 2=연속 */
    uint8       led_hazard;      /* 0=OFF, 1=BLINK */
    uint8       led_brake;       /* 0=OFF, 1=ON */
    uint8       lcd_msg_code;    /* 메시지 코드 */
} ControlCommand;

/* ── 전역 변수 (extern 선언, 정의는 Cpu0_Main.c) ── */
extern SensorData       g_sensor;
extern ControlCommand   g_command;
extern SemaphoreHandle_t xSensorMutex;
extern SemaphoreHandle_t xCommandMutex;

#endif /* APP_SENSOR_DATA_H_ */
