/**********************************************************************************************************************
 * \file state_machine.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

#include "App/sensor_data.h"
#include "FreeRTOS.h"
#include "task.h"

static RiskLevel current_state = RISK_NORMAL;
static TickType_t absent_start  = 0;
static TickType_t door_open_start = 0;

/* ── 상태 전이 ── */
static RiskLevel evaluate(SensorData *s, RiskLevel prev)
{
    boolean seated    = (s->driver == DRIVER_SEATED);
    boolean absent    = (s->driver == DRIVER_ABSENT);
    boolean door_open = (s->door == DOOR_OPEN);
    boolean door_close= (s->door == DOOR_CLOSE);
    boolean gear_p    = (s->gear == GEAR_P);
    boolean gear_dr   = (s->gear == GEAR_D || s->gear == GEAR_R);
    boolean gear_n    = (s->gear == GEAR_N);
    boolean moving    = (s->motion == MOTION_MOVING);

    /* 부재 타이머 관리 */
    if (absent && absent_start == 0)
        absent_start = xTaskGetTickCount();
    if (seated)
        absent_start = 0;

    uint32 absent_ms = 0;
    if (absent_start > 0)
        absent_ms = (xTaskGetTickCount() - absent_start) * portTICK_PERIOD_MS;

    /* SAF-01: P단 → 즉시 NORMAL */
    if (gear_p) return RISK_NORMAL;

    /* SAF-02: 착석 + 도어닫힘 → NORMAL */
    if (seated && door_close) return RISK_NORMAL;

    switch (prev)
    {
    case RISK_NORMAL:
        if (gear_dr && door_open) return RISK_WARN_LV1;
        if (gear_n  && door_open) return RISK_ROLLAWAY_WARN;
        return RISK_NORMAL;

    case RISK_WARN_LV1:
        /* SAF-03: 착석+문열림 → 10초 후 자동 해제 */
        if (seated && door_open) {
            if (door_open_start == 0)
                door_open_start = xTaskGetTickCount();
            uint32 elapsed = (xTaskGetTickCount() - door_open_start) * portTICK_PERIOD_MS;
            if (elapsed >= 10000) return RISK_NORMAL;
            return RISK_WARN_LV1;
        }
        door_open_start = 0;
        if (door_close || gear_p) return RISK_NORMAL;
        if (absent && absent_ms >= 2000) return RISK_WARN_LV2;
        return RISK_WARN_LV1;

    case RISK_WARN_LV2:
        if (seated && door_close) return RISK_NORMAL;
        if (s->gear == GEAR_D) return RISK_D_BRAKE;
        if (s->gear == GEAR_R) return RISK_R_BRAKE;
        return RISK_WARN_LV2;

    case RISK_D_BRAKE:
    case RISK_R_BRAKE:
        return RISK_BRAKE_HOLD;

    case RISK_ROLLAWAY_WARN:
        if (door_close || gear_p) return RISK_NORMAL;
        if (moving && s->speed_kmh >= 0.5f) return RISK_ROLLAWAY_BRAKE;
        return RISK_ROLLAWAY_WARN;

    case RISK_ROLLAWAY_BRAKE:
        return RISK_BRAKE_HOLD;

    case RISK_BRAKE_HOLD:
        if (seated) return RISK_RELEASE_WAIT;
        return RISK_BRAKE_HOLD;

    case RISK_RELEASE_WAIT:
        if (seated && door_close) return RISK_NORMAL;
        if (absent) return RISK_BRAKE_HOLD;
        return RISK_RELEASE_WAIT;

    default:
        return RISK_NORMAL;
    }
}

/* ── 명령 생성 ── */
static void make_command(RiskLevel state, ControlCommand *cmd)
{
    cmd->risk_level   = state;
    cmd->brake_cmd    = 0;
    cmd->motor_mode   = 0;
    cmd->buzzer_mode  = 0;
    cmd->led_hazard   = 0;
    cmd->led_brake    = 0;
    cmd->lcd_msg_code = 0;

    switch (state)
    {
    case RISK_WARN_LV1:
        cmd->buzzer_mode  = 1;
        cmd->lcd_msg_code = 1;
        break;
    case RISK_WARN_LV2:
        cmd->buzzer_mode  = 2;
        cmd->lcd_msg_code = 2;
        break;
    case RISK_D_BRAKE:
    case RISK_R_BRAKE:
    case RISK_ROLLAWAY_BRAKE:
        cmd->brake_cmd    = 1;
        cmd->buzzer_mode  = 2;
        cmd->led_hazard   = 1;
        cmd->led_brake    = 1;
        cmd->lcd_msg_code = 3;
        break;
    case RISK_BRAKE_HOLD:
        cmd->brake_cmd    = 2;
        cmd->buzzer_mode  = 2;
        cmd->led_hazard   = 1;
        cmd->led_brake    = 1;
        cmd->lcd_msg_code = 4;
        break;
    case RISK_ROLLAWAY_WARN:
        cmd->buzzer_mode  = 1;
        cmd->lcd_msg_code = 5;
        break;
    case RISK_RELEASE_WAIT:
        cmd->brake_cmd    = 2;
        cmd->led_hazard   = 1;
        cmd->led_brake    = 1;
        cmd->lcd_msg_code = 6;
        break;
    default:
        break;
    }
}

/* ══════════════════════════════════════
 *  Task_Judge: 50ms 주기
 * ══════════════════════════════════════ */
void Task_Judge(void *param)
{
    TickType_t xLastWake = xTaskGetTickCount();

    while (1)
    {
        SensorData local;

        /* 센서 데이터 복사 */
        if (xSemaphoreTake(xSensorMutex, pdMS_TO_TICKS(5)) == pdTRUE) {
            local = g_sensor;
            xSemaphoreGive(xSensorMutex);
        }

        /* 상태 전이 + 명령 생성 */
        current_state = evaluate(&local, current_state);

        ControlCommand cmd;
        make_command(current_state, &cmd);

        /* 명령 갱신 */
        if (xSemaphoreTake(xCommandMutex, pdMS_TO_TICKS(5)) == pdTRUE) {
            g_command = cmd;
            xSemaphoreGive(xCommandMutex);
        }

        vTaskDelayUntil(&xLastWake, pdMS_TO_TICKS(50));
    }
}
