/**********************************************************************************************************************
 * \file servo.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "servo.h"

#include "IfxPort.h"
#include "IfxStm.h"
#include "Bsp.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define SERVO_PORT   &MODULE_P10
#define SERVO_PIN    2

#define SERVO_PERIOD_US         20000U
#define SERVO_RIGHT_PULSE_US    750U
#define SERVO_CENTER_PULSE_US   1500U
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
static int break_state; // 1 = on, 0 = off
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
static void Servo_DelayUs(uint32 us)
{
    waitTime(IfxStm_getTicksFromMicroseconds(BSP_DEFAULT_TIMER, us));
}

static void Servo_Hold(uint32 pulseUs, uint32 holdMs)
{
    uint32 repeat = holdMs / 20U;

    for (uint32 i = 0; i < repeat; i++)
    {
        uint32 lowUs = SERVO_PERIOD_US - pulseUs;

        IfxPort_setPinHigh(SERVO_PORT, SERVO_PIN);
        Servo_DelayUs(pulseUs);

        IfxPort_setPinLow(SERVO_PORT, SERVO_PIN);
        Servo_DelayUs(lowUs);
    }
}

void Servo_Init(void)
{
    break_state = 0;
    IfxPort_setPinModeOutput(
        SERVO_PORT,
        SERVO_PIN,
        IfxPort_OutputMode_pushPull,
        IfxPort_OutputIdx_general
    );

    IfxPort_setPinLow(SERVO_PORT, SERVO_PIN);

    Servo_Hold(SERVO_CENTER_PULSE_US, 500);
}

void break_update(void)
{
    if (break_state == 1)
    {
        Servo_Hold(SERVO_CENTER_PULSE_US, 20);
    }
    else
    {
        Servo_Hold(SERVO_RIGHT_PULSE_US, 20);
    }
}

int get_break_state(void)
{
    return break_state;
}

void break_on(void)
{
    break_state = 1;
}

void break_off(void)
{
    break_state = 0;
}
