/**********************************************************************************************************************
 * \file uart_msg.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "uart_msg.h"

#include "IfxCpu.h"
#include "IfxCpu_Irq.h"
#include "IfxAsclin_Asc.h"
#include "IfxPort.h"

#include <string.h>
#include <stdio.h>
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define UART_BAUDRATE           115200
#define ASC_TX_BUFFER_SIZE      64
#define ASC_RX_BUFFER_SIZE      64

#define ISR_PRIORITY_ASC_0_TX   18
#define ISR_PRIORITY_ASC_0_RX   19
#define ISR_PRIORITY_ASC_0_EX   20
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
static IfxAsclin_Asc g_ascHandle;

/* FIFO buffers */
static uint8 g_ascTxBuffer[ASC_TX_BUFFER_SIZE + sizeof(Ifx_Fifo) + 8];
static uint8 g_ascRxBuffer[ASC_RX_BUFFER_SIZE + sizeof(Ifx_Fifo) + 8];

/* ---------------- UART ISR ---------------- */
IFX_INTERRUPT(ASC_Tx0IntHandler, 0, ISR_PRIORITY_ASC_0_TX);
IFX_INTERRUPT(ASC_Rx0IntHandler, 0, ISR_PRIORITY_ASC_0_RX);
IFX_INTERRUPT(ASC_Err0IntHandler, 0, ISR_PRIORITY_ASC_0_EX);
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
void ASC_Tx0IntHandler(void)
{
    IfxAsclin_Asc_isrTransmit(&g_ascHandle);
}

void ASC_Rx0IntHandler(void)
{
    IfxAsclin_Asc_isrReceive(&g_ascHandle);
}

void ASC_Err0IntHandler(void)
{
    IfxAsclin_Asc_isrError(&g_ascHandle);
}

/* ---------------- UART Init ---------------- */
void Driver_Asc0_Init(void)
{
    IfxAsclin_Asc_Config ascConfig;
    IfxAsclin_Asc_initModuleConfig(&ascConfig, &MODULE_ASCLIN0);

    ascConfig.baudrate.prescaler    = 1;
    ascConfig.baudrate.baudrate     = UART_BAUDRATE;
    ascConfig.baudrate.oversampling = IfxAsclin_OversamplingFactor_4;

    ascConfig.interrupt.txPriority    = ISR_PRIORITY_ASC_0_TX;
    ascConfig.interrupt.rxPriority    = ISR_PRIORITY_ASC_0_RX;
    ascConfig.interrupt.erPriority    = ISR_PRIORITY_ASC_0_EX;
    ascConfig.interrupt.typeOfService = IfxSrc_Tos_cpu0;

    ascConfig.txBuffer     = g_ascTxBuffer;
    ascConfig.txBufferSize = ASC_TX_BUFFER_SIZE;
    ascConfig.rxBuffer     = g_ascRxBuffer;
    ascConfig.rxBufferSize = ASC_RX_BUFFER_SIZE;

    const IfxAsclin_Asc_Pins pins = {
        NULL_PTR,                    IfxPort_InputMode_pullUp,
        &IfxAsclin0_RXA_P14_1_IN,    IfxPort_InputMode_pullUp,
        NULL_PTR,                    IfxPort_OutputMode_pushPull,
        &IfxAsclin0_TX_P14_0_OUT,    IfxPort_OutputMode_pushPull,
        IfxPort_PadDriver_cmosAutomotiveSpeed1
    };
    ascConfig.pins = &pins;

    IfxAsclin_Asc_initModule(&g_ascHandle, &ascConfig);
}

/* ---------------- UART Text Send ---------------- */
void UART_sendText(const char *text)
{
    Ifx_SizeT count = (Ifx_SizeT)strlen(text);
    IfxAsclin_Asc_write(&g_ascHandle, (uint8 *)text, &count, TIME_INFINITE);
}

/* ---------------- UART Text Send ---------------- */
void sendData(int warning, int brake, int gear, int door, int driver, int speed)
{
    unsigned short status = 0;
    char binStr[17];   // 16비트 + '\0'
    int i;

    status |= ((warning & 0x03) << 14);  // 2bit
    status |= ((brake   & 0x03) << 12);  // 2bit
    status |= ((gear    & 0x03) << 10);  // 2bit
    status |= ((door    & 0x01) << 9);   // 1bit
    status |= ((driver  & 0x01) << 8);   // 1bit
    status |=  (speed   & 0xFF);         // 8bit

    for (i = 0; i < 16; i++)
    {
        binStr[i] = ((status >> (15 - i)) & 1) ? '1' : '0';
    }
    binStr[16] = '\0';

    UART_sendText(binStr);
    UART_sendText("\r\n");
}
