/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#include "IfxMultican_Can.h"

#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxStm.h"

#include "IfxPort.h"
#include "IfxPort_PinMap.h"
#include "Platform_Types.h"
#include "IfxPort_reg.h"
#include "Gtm/Tom/Pwm/IfxGtm_Tom_Pwm.h"
#include "IfxGtm_PinMap.h"


#include "lcd.h"
#include "driver_lcd.h"
#include "driver_stm.h"
#include "driver_msg.h"
#include "driver_can.h"
#include "driver_gpio.h"

IfxCpu_syncEvent cpuSyncEvent = 0;

//macro



//function declaration
// scheduler
void app_scheduling(void);
void app_task_1ms(void);
void app_task_10ms(void);
void app_task_100ms(void);
void app_task_1000ms(void);

//test
void can_loopback(void);

//user types declaration

//global variable declaration
char str1[33] = "good morning. i'm so tired. bye!";
char str2[33] = "good morning. i'm so tired. bye!";

volatile uint8 g_risk_level;
volatile uint8 g_driver_present;
volatile uint8 g_door_state;
volatile uint8 g_gear_state;
volatile uint32   g_speed;
volatile uint8 g_break;

static volatile boolean data_received_flag;

static volatile uint8 can_main_timeout_cnt;
static volatile uint8 can_act_timeout_cnt;
static volatile uint8 can_main_timeout_flag;
static volatile boolean can_act_timeout_flag;

static volatile uint8 led_emergency_cnt;
static volatile uint8 buz_cnt;

//lcd, uart전용
static volatile uint8 warn;
static volatile uint8 brk;
static volatile uint8 speed;

static volatile uint8 notice;

//static variable declaration


//interrupt


void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);

    gpio_init();
    driver_lcd_init();
    driver_stm_init();
    driver_asc_Init();
    init_can();


    print_lcd(str1, str2);
    while(1)
    {
        app_scheduling();

    }
}


void app_scheduling(void)
{
    if (g_scheduling_info.scheduling_1ms_flag == 1u)
    {
        g_scheduling_info.scheduling_1ms_flag = 0u;
        app_task_1ms();

        /* 하위 주기 판단: 중첩 구조 유지 */
        if (g_scheduling_info.scheduling_10ms_flag == 1u)
        {
            g_scheduling_info.scheduling_10ms_flag = 0u;
            app_task_10ms();
        }

        if (g_scheduling_info.scheduling_100ms_flag == 1u)
        {
            g_scheduling_info.scheduling_100ms_flag = 0u;
            app_task_100ms();
        }

        if (g_scheduling_info.scheduling_1000ms_flag == 1u)
        {
            g_scheduling_info.scheduling_1000ms_flag = 0u;
            app_task_1000ms();
        }
    }
}
void app_task_1ms(void)
{




}
void app_task_10ms(void)
{



}
void app_task_100ms(void)
{
    static uint8 before_risk = 0;
    static uint8 current_risk = 0;

    //can timeout
    can_main_timeout_cnt++;
    can_act_timeout_cnt++;


    if(g_clu_status_received)
    {
        g_risk_level = ((g_clu_status_dataLow >> 0) & 0xff);
        g_driver_present = ((g_clu_status_dataLow >> 8) & 0xff);
        g_door_state = ((g_clu_status_dataLow >> 16) & 0xff);
        g_gear_state = ((g_clu_status_dataLow >> 24) & 0xff);

        before_risk = current_risk;
        current_risk = g_risk_level;


        //여기서 데이터 변환
        if(g_risk_level == 0) warn = UART_WARN_NONE;
        else if(g_risk_level == 1) warn = UART_WARN_LV1;
        else if(g_risk_level == 2) warn = UART_WARN_LV2;
        else if(g_risk_level == 3) warn = UART_WARN_ROLLAWAY;

        if(g_risk_level < 4) brk = UART_BRK_NONE;
        else if(g_risk_level == 4) brk = UART_BRK_D;
        else if(g_risk_level == 5) brk = UART_BRK_R;
        else if(g_risk_level == 6) brk = UART_BRK_ROLLAWAY;


        can_main_timeout_cnt = 0;
        can_main_timeout_flag = FALSE;
        g_clu_status_received = FALSE;
        data_received_flag = TRUE;
    }

    if(g_act_feedback_received)
    {
        g_speed = g_act_feedback_dataLow;
        g_break = g_act_feedback_dataHigh & 0xff;

        //여기서 데이터 변환
        speed = (uint8)g_speed;


        can_act_timeout_cnt = 0;
        can_act_timeout_flag = FALSE;
        g_act_feedback_received = FALSE;
        data_received_flag = TRUE;
    }

    //can timeout execution
    if(can_main_timeout_cnt >= 3) can_main_timeout_flag = TRUE;
    if(can_act_timeout_cnt >= 3) can_act_timeout_flag = TRUE;

    if(can_main_timeout_flag)
    {
        g_risk_level = 7;
        data_received_flag = TRUE;
    }

    if(can_act_timeout_flag)
    {
        speed = 0xff;
        data_received_flag = TRUE;
    }


    //lcd, uart
    if(data_received_flag)
    {
        print_lcd(str1, str2);
        lcd_make_strings(g_risk_level, g_break, g_gear_state, g_door_state, g_driver_present, speed, notice, str1, str2);
        if((g_risk_level != 7) && (before_risk != g_risk_level))   sendData(warn, brk, g_gear_state, g_door_state, g_driver_present, speed);

        data_received_flag = FALSE;
    }


    //break led
    if(g_break) led_on(led_break);
    else led_off(led_break);

    //emergency led
    if(g_risk_level && (g_risk_level != 3))
    {
        if(led_emergency_cnt == 0) led_on(led_emergency);
        led_emergency_cnt++;
        if(led_emergency_cnt >= 11)
        {
            led_toggle(led_emergency);
            led_emergency_cnt = 1;
        }
    }
    else
    {
        led_emergency_cnt = 0;
        led_off(led_emergency);
    }

    //buz
    if((g_risk_level >= 1) && (g_risk_level < 7))
    {
        if(buz_cnt == 0) buz_on(buz_warning);       // 첫 진입: 즉시 ON
        buz_cnt++;
        if(g_risk_level == 1)                        // 1초 토글
        {
            if(buz_cnt >= 11)
            {
                buz_toggle(buz_warning);
                buz_cnt = 1;
            }
        }
        else if(g_risk_level == 2)                   // 0.3초 토글
        {
            if(buz_cnt >= 4)
            {
                buz_toggle(buz_warning);
                buz_cnt = 1;
            }
        }
        else if(g_risk_level == 3)                   // 0.1초 단발 (1회 ON 후 OFF 유지)
        {
            if(buz_cnt >= 2)
            {
                buz_off(buz_warning);
                // cnt 더 이상 증가 안 시킴 → 단발 1회로 끝
            }
        }
        // g_risk_level >= 4: 상시 ON → 토글/OFF 없이 유지
        else buz_cnt = 0;
    }
    else
    {
        buz_cnt = 0;
        buz_off(buz_warning);
    }

    uint16 data = 0x0300;

    IfxMultican_Message tx100msg = {
                    .id = 0x100,
                    .lengthCode = IfxMultican_DataLengthCode_4,
                    .data[0] = data,
                    .data[1] = 0,
                    .fastBitRate = FALSE};
    //IfxMultican_Can_MsgObj_sendMessage(&txMsgObj1, &tx100msg);

}
void app_task_1000ms(void)
{
    //can_loopback();
    if(g_risk_level && (g_risk_level != 7) && (g_risk_level != 3)) notice = 1 - notice;
    else notice = 0;
}



void can_loopback(void)
{
    uint32 data = 0;
        static int i = 0;
        static int j = 0;
        static int k = 0;
        static int t = 0;

        data = (i << 24) | (j << 16) | (k << 8) | t;

        t++;
        if(t > 3)
        {
            k++;
            t = 0;
        }
        if(k > 2)
        {
            k = 0;
            j++;
        }
        if(j > 2)
        {
            j = 0;
            i++;
        }
        if(i > 6)
        {
            i = 0;
        }



        IfxMultican_Message tx200msg = {
                .id = 0x200,
                .lengthCode = IfxMultican_DataLengthCode_4,
                .data[0] = data,
                .data[1] = 0,
                .fastBitRate = FALSE};
        IfxMultican_Message tx300msg = {
                    .id = 0x300,
                    .lengthCode = IfxMultican_DataLengthCode_5,
                    .data[0] = data,
                    .data[1] = (g_risk_level > 3),
                    .fastBitRate = FALSE};
        IfxMultican_Can_MsgObj_sendMessage(&txMsgObj1, &tx200msg);
        IfxMultican_Can_MsgObj_sendMessage(&txMsgObj2, &tx300msg);
}



