/**********************************************************************************************************************
 * \file driver_i2c.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "driver_lcd.h"
#include "IfxPort_PinMap.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
IfxI2c_I2c i2c;
IfxI2c_I2c_Device i2cDev;
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
static void i2c_init(void);
static void lcd_1byte_write(uint8 data, uint8 control);
static void lcd_4bit_write(uint8 data);
static void pin_disable(void);
void print_lcd(const char* lcd1, const char* lcd2);
/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
static void i2c_init(void)
{
    //module
    IfxI2c_I2c_Config config;
    IfxI2c_I2c_initConfig(&config, &MODULE_I2C0);

    const IfxI2c_Pins pins1 = {
            SCL_PIN1,
            SDA_PIN1,
            IfxPort_PadDriver_cmosAutomotiveSpeed1
    };
    config.pins = &pins1;
    config.baudrate = BAUDRATE;
    IfxI2c_I2c_initModule(&i2c, &config);

    //pin 2 setting
    const IfxI2c_Pins pins2 = {
            SCL_PIN2,
            SDA_PIN2,
            IfxPort_PadDriver_cmosAutomotiveSpeed1
    };
    config.pins = &pins2;
    IfxI2c_stop(config.i2c);

    if (config.pins != NULL_PTR)
    {
        IfxI2c_initSclSdaPin(config.pins->scl, config.pins->sda, config.pins->padDriver);
    }

    IfxI2c_run(config.i2c);

    i2c.busStatus = IfxI2c_getBusStatus(config.i2c);
    i2c.status    = IfxI2c_I2c_Status_ok;


    //device
    IfxI2c_I2c_deviceConfig i2cDeviceConfig;
    IfxI2c_I2c_initDeviceConfig(&i2cDeviceConfig, &i2c);

    i2cDeviceConfig.deviceAddress = (SLAVE_ADD << 1); // always shift 1bit, slave ad
    IfxI2c_I2c_initDevice(&i2cDev, &i2cDeviceConfig);
}

void driver_lcd_init(void)
{
    i2c_init();
    //only for init
    IfxStm_wait(10000000);

    IfxI2c_initSclSdaPin(&IfxI2c0_SCL_P13_1_INOUT,
                &IfxI2c0_SDA_P13_2_INOUT,
                IfxPort_PadDriver_cmosAutomotiveSpeed1);
    lcd_4bit_write(0x30u);
    lcd_4bit_write(0x30u);
    lcd_4bit_write(0x30u);
    lcd_4bit_write(0x20u);

    lcd_4bit_write(0x20u);
    lcd_4bit_write(0x80u);

    lcd_4bit_write(0x00u);
    lcd_4bit_write(0x80u);

    lcd_4bit_write(0x00u);
    lcd_4bit_write(0x10u);

    lcd_4bit_write(0x00u);
    lcd_4bit_write(0x60u);

    lcd_4bit_write(0x00u);
    lcd_4bit_write(0xc0u);

    IfxI2c_initSclSdaPin(&IfxI2c0_SCL_P15_4_INOUT,
                &IfxI2c0_SDA_P15_5_INOUT,
                IfxPort_PadDriver_cmosAutomotiveSpeed1);
    lcd_4bit_write(0x30u);
    lcd_4bit_write(0x30u);
    lcd_4bit_write(0x30u);
    lcd_4bit_write(0x20u);

    lcd_4bit_write(0x20u);
    lcd_4bit_write(0x80u);

    lcd_4bit_write(0x00u);
    lcd_4bit_write(0x80u);

    lcd_4bit_write(0x00u);
    lcd_4bit_write(0x10u);

    lcd_4bit_write(0x00u);
    lcd_4bit_write(0x60u);

    lcd_4bit_write(0x00u);
    lcd_4bit_write(0xc0u);
}

static void lcd_1byte_write(uint8 data, uint8 control)
{
    uint8 packet = (data & 0xf0) | 0x04 | control;
    IfxI2c_I2c_write(&i2cDev, &packet, 1);
    packet &= ~0x04;
    IfxI2c_I2c_write(&i2cDev, &packet, 1);

    packet = ((data << 4) & 0xf0) | 0x04 | control;
    IfxI2c_I2c_write(&i2cDev, &packet, 1);
    packet &= ~0x04;
    IfxI2c_I2c_write(&i2cDev, &packet, 1);
}

static void lcd_4bit_write(uint8 data)
{
    uint8 packet = data | 0x0c;
    IfxI2c_I2c_write(&i2cDev, &packet, 1);
    IfxStm_wait(500000);
    packet = data | 0x08;
    IfxI2c_I2c_write(&i2cDev, &packet, 1);
    IfxStm_wait(500000);
}

static void pin_disable(void)
{
    IfxPort_setPinModeInput(IfxPort_P13_1.port, IfxPort_P13_1.pinIndex, IfxPort_InputMode_pullUp);
    IfxPort_setPinModeInput(IfxPort_P13_2.port, IfxPort_P13_2.pinIndex, IfxPort_InputMode_pullUp);
    IfxPort_setPinModeInput(IfxPort_P15_4.port, IfxPort_P15_4.pinIndex, IfxPort_InputMode_pullUp);
    IfxPort_setPinModeInput(IfxPort_P15_5.port, IfxPort_P15_5.pinIndex, IfxPort_InputMode_pullUp);
}

void print_lcd(const char* lcd1, const char* lcd2)
{
    pin_disable();
    IfxI2c_initSclSdaPin(&IfxI2c0_SCL_P13_1_INOUT,
            &IfxI2c0_SDA_P13_2_INOUT,
            IfxPort_PadDriver_cmosAutomotiveSpeed1);

    //주소 이동
    lcd_1byte_write(0x80|0x00, 0x08);
    int i;
    for(i = 0; i < 16; i++)
        lcd_1byte_write(lcd1[i], 0x09);

    //주소 이동
    lcd_1byte_write(0x80|0x40, 0x08);
    for(i = 16; i < 32; i++)
        lcd_1byte_write(lcd1[i], 0x09);

    pin_disable();
    IfxI2c_initSclSdaPin(&IfxI2c0_SCL_P15_4_INOUT,
            &IfxI2c0_SDA_P15_5_INOUT,
            IfxPort_PadDriver_cmosAutomotiveSpeed1);

    //주소 이동
    lcd_1byte_write(0x80|0x00, 0x08);
    for(i = 0; i < 16; i++)
        lcd_1byte_write(lcd2[i], 0x09);

    //주소 이동
    lcd_1byte_write(0x80|0x40, 0x08);
    for(i = 16; i < 32; i++)
        lcd_1byte_write(lcd2[i], 0x09);
}
