/**********************************************************************************************************************
 * \file driver_can.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "driver_can.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
static IfxMultican_Can mcan;
static IfxMultican_Can_Node canNode0, canNode1;
volatile uint8 isr_cnt;

//for loopback
IfxMultican_Can_MsgObj txMsgObj1;
IfxMultican_Can_MsgObj txMsgObj2;
IfxMultican_Can_MsgObj rxMsgObj1;
IfxMultican_Can_MsgObj rxMsgObj2;

//for can
IfxMultican_Can_MsgObj  rx_clu_status;
IfxMultican_Can_MsgObj  rx_act_feedback;

//IfxMultican_Message rxmsg;
//IfxMultican_Message txmsg = { 0x152, IfxMultican_DataLengthCode_1, 0, 1, FALSE};

/* 수신 완료 플래그 (ISR에서 세팅, 메인 루프에서 확인 후 클리어) */
volatile boolean g_clu_status_received;
volatile boolean g_act_feedback_received;

/* 수신된 데이터 저장용 */
volatile uint32  g_clu_status_dataLow;
volatile uint32  g_clu_status_dataHigh;
volatile uint32  g_act_feedback_dataLow;
volatile uint32  g_act_feedback_dataHigh;
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
void init_can_loopback(void)
{
    // 1. 모듈 초기화
    IfxMultican_Can_Config canConfig;
    IfxMultican_Can_initModuleConfig(&canConfig, &MODULE_CAN); // 기본값 할당
    IfxMultican_Can_initModule(&mcan, &canConfig);             // 하드웨어 적용

    // 2. 노드 초기화(루프백을 위해 노드 2개)
    IfxMultican_Can_NodeConfig canNodeConfig;
    IfxMultican_Can_Node_initConfig(&canNodeConfig, &mcan);
    canNodeConfig.nodeId = IfxMultican_NodeId_0;
    canNodeConfig.baudrate = 500000; // 500kbps 속도 설정

    canNodeConfig.loopBackMode = TRUE;
    IfxMultican_Can_Node_init(&canNode0, &canNodeConfig);

    IfxMultican_Can_Node_initConfig(&canNodeConfig, &mcan);
    canNodeConfig.nodeId = IfxMultican_NodeId_1;
    canNodeConfig.baudrate = 500000; // 500kbps 속도 설정

    canNodeConfig.loopBackMode = TRUE;
    IfxMultican_Can_Node_init(&canNode1, &canNodeConfig);

    //3. MO 초기화
    // 송신 MO 하드웨어 적용
    IfxMultican_Can_MsgObjConfig canMsgObjConfig;
    IfxMultican_Can_MsgObj_initConfig(&canMsgObjConfig, &canNode0);

    canMsgObjConfig.msgObjId = 0; // 송신용으로 할당할 MO 번호 (예: 0번)
    canMsgObjConfig.messageId = 0x200; // 전송할 타겟 CAN ID
    canMsgObjConfig.frame = IfxMultican_Frame_transmit; // 프레임 방향을 송신으로 설정
    canMsgObjConfig.control.messageLen = IfxMultican_DataLengthCode_8; // DLC를 8바이트로 설정


    IfxMultican_Can_MsgObj_init(&txMsgObj1, &canMsgObjConfig);

    // 송신 MO 하드웨어 적용
    IfxMultican_Can_MsgObj_initConfig(&canMsgObjConfig, &canNode0);

    canMsgObjConfig.msgObjId = 1; // 송신용으로 할당할 MO 번호 (예: 0번)
    canMsgObjConfig.messageId = 0x300; // 전송할 타겟 CAN ID
    canMsgObjConfig.frame = IfxMultican_Frame_transmit; // 프레임 방향을 송신으로 설정
    canMsgObjConfig.control.messageLen = IfxMultican_DataLengthCode_8; // DLC를 8바이트로 설정

    IfxMultican_Can_MsgObj_init(&txMsgObj2, &canMsgObjConfig);

    // 수신 MO 하드웨어 적용
    IfxMultican_Can_MsgObj_initConfig(&canMsgObjConfig, &canNode1);

    canMsgObjConfig.msgObjId = 2;          // 사용할 MO 번호
    canMsgObjConfig.messageId = 0x200;      // 타겟 ID
    canMsgObjConfig.acceptanceMask = 0x7FF; // 11비트 완벽 일치 마스크
    canMsgObjConfig.frame = IfxMultican_Frame_receive; // 수신 모드

    /* 수신 인터럽트 설정 */
    canMsgObjConfig.rxInterrupt.enabled       = TRUE;
    canMsgObjConfig.rxInterrupt.srcId         = CAN_RX_INTERRUPT_SRC_ID;

    IfxMultican_Can_MsgObj_init(&rxMsgObj1, &canMsgObjConfig);

    // 수신 MO 하드웨어 적용
    IfxMultican_Can_MsgObj_initConfig(&canMsgObjConfig, &canNode1);

    canMsgObjConfig.msgObjId = 3;          // 사용할 MO 번호
    canMsgObjConfig.messageId = 0x300;      // 타겟 ID
    canMsgObjConfig.acceptanceMask = 0x7FF; // 11비트 완벽 일치 마스크
    canMsgObjConfig.frame = IfxMultican_Frame_receive; // 수신 모드

    /* 수신 인터럽트 설정 */
    canMsgObjConfig.rxInterrupt.enabled       = TRUE;
    canMsgObjConfig.rxInterrupt.srcId         = CAN_RX_INTERRUPT_SRC_ID;

    IfxMultican_Can_MsgObj_init(&rxMsgObj2, &canMsgObjConfig);

    /* 인터럽트 우선순위 및 서비스 프로바이더 설정 */
    volatile Ifx_SRC_SRCR *src = IfxMultican_getSrcPointer(&MODULE_CAN, CAN_RX_INTERRUPT_SRC_ID);
    IfxSrc_init(src, CAN_RX_INTERRUPT_PROVIDER, CAN_RX_INTERRUPT_PRIORITY);
    IfxSrc_enable(src);
}

void init_can(void)
{
    // 1. 모듈 초기화
    IfxMultican_Can_Config canConfig;
    IfxMultican_Can_initModuleConfig(&canConfig, &MODULE_CAN); // 기본값 할당
    IfxMultican_Can_initModule(&mcan, &canConfig);             // 하드웨어 적용

    // 2. 노드 초기화
    IfxMultican_Can_NodeConfig canNodeConfig;
    IfxMultican_Can_Node_initConfig(&canNodeConfig, &mcan);
    canNodeConfig.nodeId = IfxMultican_NodeId_0;
    canNodeConfig.baudrate = 500000; // 500kbps 속도 설정

    canNodeConfig.rxPin = &IfxMultican_RXD0B_P20_7_IN;
    canNodeConfig.txPin = &IfxMultican_TXD0_P20_8_OUT;
    IfxMultican_Can_Node_init(&canNode0, &canNodeConfig);

    //3. MO 초기화(송신, 수신) ( 송신 없음 )
    IfxMultican_Can_MsgObjConfig canMsgObjConfig;


    IfxMultican_Can_MsgObj_initConfig(&canMsgObjConfig, &canNode0);

    canMsgObjConfig.msgObjId = 1;          // 사용할 MO 번호
    canMsgObjConfig.messageId = 0x200;      // 타겟 ID
    canMsgObjConfig.acceptanceMask = 0x7FF; // 11비트 완벽 일치 마스크
    canMsgObjConfig.frame = IfxMultican_Frame_receive; // 수신 모드

    /* 수신 인터럽트 설정 */
    canMsgObjConfig.rxInterrupt.enabled       = TRUE;
    canMsgObjConfig.rxInterrupt.srcId         = CAN_RX_INTERRUPT_SRC_ID;

    // 수신 MO 하드웨어 적용
    IfxMultican_Can_MsgObj_init(&rx_clu_status, &canMsgObjConfig);


    IfxMultican_Can_MsgObj_initConfig(&canMsgObjConfig, &canNode0);

    canMsgObjConfig.msgObjId = 2;          // 사용할 MO 번호
    canMsgObjConfig.messageId = 0x300;      // 타겟 ID
    canMsgObjConfig.acceptanceMask = 0x7FF; // 11비트 완벽 일치 마스크
    canMsgObjConfig.frame = IfxMultican_Frame_receive; // 수신 모드

    /* 수신 인터럽트 설정 */
    canMsgObjConfig.rxInterrupt.enabled       = TRUE;
    canMsgObjConfig.rxInterrupt.srcId         = CAN_RX_INTERRUPT_SRC_ID;

    // 수신 MO 하드웨어 적용
    IfxMultican_Can_MsgObj_init(&rx_act_feedback, &canMsgObjConfig);

////////////////////////////////////////////////////////
    IfxMultican_Can_MsgObj_initConfig(&canMsgObjConfig, &canNode0);

    canMsgObjConfig.msgObjId = 0; // 송신용으로 할당할 MO 번호 (예: 0번)
    canMsgObjConfig.messageId = 0x100; // 전송할 타겟 CAN ID
    canMsgObjConfig.frame = IfxMultican_Frame_transmit; // 프레임 방향을 송신으로 설정
    canMsgObjConfig.control.messageLen = IfxMultican_DataLengthCode_2; // DLC를 8바이트로 설정


    IfxMultican_Can_MsgObj_init(&txMsgObj1, &canMsgObjConfig);
/////////////////////////////////////////////////
    /* 인터럽트 우선순위 및 서비스 프로바이더 설정 */
    volatile Ifx_SRC_SRCR *src = IfxMultican_getSrcPointer(&MODULE_CAN, CAN_RX_INTERRUPT_SRC_ID);
    IfxSrc_init(src, CAN_RX_INTERRUPT_PROVIDER, CAN_RX_INTERRUPT_PRIORITY);
    IfxSrc_enable(src);

}


void canRxISR(void)
{
    IfxMultican_Message msg;

    // MO1 (rx_clu_status, ID=0x200) 수신 확인
    if (IfxMultican_Can_MsgObj_isRxPending(&rx_clu_status))
    {
        IfxMultican_Can_MsgObj_readMessage(&rx_clu_status, &msg);

        g_clu_status_dataLow  = msg.data[0];
        g_clu_status_dataHigh = msg.data[1];
        g_clu_status_received = TRUE;
        isr_cnt++;
    }

    // MO2 (rx_act_feedback, ID=0x300) 수신 확인
    if (IfxMultican_Can_MsgObj_isRxPending(&rx_act_feedback))
    {
        IfxMultican_Can_MsgObj_readMessage(&rx_act_feedback, &msg);

        g_act_feedback_dataLow  = msg.data[0];
        g_act_feedback_dataHigh = msg.data[1];
        g_act_feedback_received = TRUE;
    }


    /*
    //for loopback
    //////////////////////////////////////////////////////
    // MO1 (rx_clu_status, ID=0x200) 수신 확인
   if (IfxMultican_Can_MsgObj_isRxPending(&rxMsgObj1))
   {
       IfxMultican_Can_MsgObj_readMessage(&rxMsgObj1, &msg);

       g_clu_status_dataLow  = msg.data[0];
       g_clu_status_dataHigh = msg.data[1];
       g_clu_status_received = TRUE;
   }

   // MO2 (rx_act_feedback, ID=0x300) 수신 확인
   if (IfxMultican_Can_MsgObj_isRxPending(&rxMsgObj2))
   {
       IfxMultican_Can_MsgObj_readMessage(&rxMsgObj2, &msg);

       g_act_feedback_dataLow  = msg.data[0];
       g_act_feedback_dataHigh = msg.data[1];
       g_act_feedback_received = TRUE;
   }
   */
}
