/**********************************************************************************************************************
 * \file driver_can.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef DRIVER_CAN_H_
#define DRIVER_CAN_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "IfxMultican_Can.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define CAN_RX_INTERRUPT_SRC_ID     IfxMultican_SrcId_0
#define CAN_RX_INTERRUPT_PRIORITY 50
#define CAN_RX_INTERRUPT_PROVIDER   IfxSrc_Tos_cpu0

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

extern IfxMultican_Can_MsgObj txMsgObj1;
extern IfxMultican_Can_MsgObj txMsgObj2;
extern IfxMultican_Can_MsgObj rxMsgObj1;
extern IfxMultican_Can_MsgObj rxMsgObj2;

extern IfxMultican_Can_MsgObj  rx_clu_status;
extern IfxMultican_Can_MsgObj  rx_act_feedback;

/* 수신 완료 플래그 (ISR에서 세팅, 메인 루프에서 확인 후 클리어) */
extern volatile boolean g_clu_status_received;
extern volatile boolean g_act_feedback_received;

/* 수신된 데이터 저장용 */
extern volatile uint32  g_clu_status_dataLow;
extern volatile uint32  g_clu_status_dataHigh;
extern volatile uint32  g_act_feedback_dataLow;
extern volatile uint32  g_act_feedback_dataHigh;

/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/
 
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
void init_can_loopback(void);
void init_can(void);
void canRxISR(void);

IFX_INTERRUPT(canRxISR, 0, CAN_RX_INTERRUPT_PRIORITY);

#endif /* DRIVER_CAN_H_ */
