/**********************************************************************************************************************
 * \file lcd.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Platform_Types.h"
#include <stdio.h>
#include <string.h>

#include "lcd.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

static char lcd_get_gear_char(uint8 gear)
{
    switch (gear) {
    case LCD_GEAR_P: return 'P';
    case LCD_GEAR_R: return 'R';
    case LCD_GEAR_N: return 'N';
    case LCD_GEAR_D: return 'D';
    default:         return '?';
    }
}

static char lcd_get_driver_char(uint8 driver)
{
    return (driver == LCD_DRIVER_PRESENT) ? 'O' : 'X';
}

static char lcd_get_door_char(uint8 door)
{
    return (door == LCD_DOOR_CLOSE) ? 'O' : 'X';
}

static const char* lcd_get_risk_keyword(uint8 warning)
{
    /* alert warning 기준 */
    switch (warning) {
    case LCD_WARN_LV1:       return "W1"; /* RISK_WARN_LV1 */
    case LCD_WARN_LV2:       return "W2"; /* RISK_WARN_LV2 */
    case LCD_WARN_ROLLAWAY:  return "W3"; /* RISK_ROLLAWAY_WARN */
    case LCD_BRK_D:          return "B1";  /* RISK_D_BRAKE */
    case LCD_BRK_R:          return "B2";  /* RISK_R_BRAKE */
    case LCD_BRK_ROLLAWAY:   return "B3";  /* RISK_ROLLAWAY_BRAKE */
    default:                 return "OK"; /* RISK_NORMAL */
    }
}

static const char* lcd_get_brk_text(uint8 brake)
{
    return (brake == LCD_BRK_NONE) ? "OFF" : "ON ";
}

static uint8 lcd_get_motor_mode(uint8 gear, uint8 brake)
{
    /* brake가 걸리면 STOP */
    if (brake != LCD_BRK_NONE) {
        return 0; /* STOP */
    }

    switch (gear) {
    case LCD_GEAR_D: return 1; /* FWD */
    case LCD_GEAR_R: return 2; /* REV */
    case LCD_GEAR_N: return 3; /* NEUTRAL */
    case LCD_GEAR_P: return 4; /* PARK */
    default:         return 0; /* STOP */
    }
}

static uint8 lcd_get_buzzer_mode(uint8 warning, uint8 brake)
{
    if (brake != LCD_BRK_NONE) {
        return 2; /* 연속 경고 */
    }

    switch (warning) {
    case LCD_WARN_LV1:       return 1; /* 1초 경고 */
    case LCD_WARN_LV2:       return 2; /* 0.3초 경고 */
    case LCD_WARN_ROLLAWAY:  return 2; /* 단속 경고 */
    case LCD_WARN_NONE:
    default:                 return 0; /* 부저 OFF */
    }
}

static uint8 lcd_get_led_hazard(uint8 warning)
{
    return (warning == LCD_WARN_NONE) ? 0 : 1;
}

static uint8 lcd_get_led_brake(uint8 brake)
{
    return (brake == LCD_BRK_NONE) ? 0 : 1;
}


/* --------------------------------
 * 32글자 LCD 문자열 생성 함수
 *
 * out_lcd1:
 * [0..15]  = "G ---km move    "
 * [16..31] = "driver - door - "
 *
 * out_lcd2:
 * [0..15]  = "RISK:__ BRK:___ "
 * [16..31] = "M:_ S:_ L:_ B:_ "
 *
 * 각 버퍼는 최소 33바이트 필요
 * -------------------------------- */
void lcd_make_strings(uint8 warning, uint8 brake, uint8 gear,
    uint8 door, uint8 driver, uint8 speed, uint8 notice,
    char out_lcd1[33], char out_lcd2[33])
{
    char line1_1[17];
    char line1_2[17];
    char line2_1[17];
    char line2_2[17];
    char notice_1[17] = "  Sit in seat  &";
    char notice_2[17] = " Close the door ";

    char gear_ch = lcd_get_gear_char(gear);
    char driver_ch = lcd_get_driver_char(driver);
    char door_ch = lcd_get_door_char(door);

    const char* risk_txt = lcd_get_risk_keyword(warning);
    const char* brk_txt = lcd_get_brk_text(brake);

    uint8 motor_mode = lcd_get_motor_mode(gear, brake);
    uint8 buzzer_mode = lcd_get_buzzer_mode(warning, brake);
    uint8 led_hazard = lcd_get_led_hazard(warning);
    uint8 led_brake = lcd_get_led_brake(brake);

    /* LCD 1 */
    /* "D ---km move    " */
    if(speed == 0xff)
    {
        snprintf(line1_1, sizeof(line1_1),
            "%c ---km move    ",
            gear_ch);
    }
    else if(speed == 0)
    {
        snprintf(line1_1, sizeof(line1_1),
            "%c 000km stop    ",
            gear_ch);
    }
    else
    {
        snprintf(line1_1, sizeof(line1_1),
            "%c %03ukm move    ",
            gear_ch, (unsigned int)speed);
    }



    /* "driver - door - " */
    snprintf(line1_2, sizeof(line1_2),
        "driver %c door %c ",
        driver_ch, door_ch);


    /* LCD 2 */
    if(warning == 7)
    {
        snprintf(line2_1, sizeof(line2_1),
            "    MAIN CAN    ");

        /* "M:- S:- L:- B:- " */
        snprintf(line2_2, sizeof(line2_2),
            "  DISCONNECTED  ");
    }
    else
    {
        /* 예: "RISK:W1 BRK:OFF " / "RISK:R2 BRK:ON  " */
        snprintf(line2_1, sizeof(line2_1),
            "RISK:%2s BRK:%-3s ",
            risk_txt, brk_txt);

        /* "M:- S:- L:- B:- " */
        snprintf(line2_2, sizeof(line2_2),
            "M:%u S:%u L:%u B:%u ",
            (unsigned int)motor_mode,
            (unsigned int)buzzer_mode,
            (unsigned int)led_hazard,
            (unsigned int)led_brake);
    }


    /* 32글자 고정 문자열 생성 */
    if(notice)
    {
        memcpy(&out_lcd1[0], notice_1, 16);
        memcpy(&out_lcd1[16], notice_2, 16);
        out_lcd1[32] = '\0';
    }
    else
    {
        memcpy(&out_lcd1[0], line1_1, 16);
        memcpy(&out_lcd1[16], line1_2, 16);
        out_lcd1[32] = '\0';

    }

    memcpy(&out_lcd2[0], line2_1, 16);
    memcpy(&out_lcd2[16], line2_2, 16);
    out_lcd2[32] = '\0';

}
