/**********************************************************************************************************************
 * \file lcd.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef LCD_H_
#define LCD_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Platform_Types.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
/* -----------------------------
 * 입력값 코드 정의
 * ----------------------------- */

 /* warning_type (2bit)
  * 0: 경고 없음
  * 1: 1차 경고
  * 2: 강화 경고
  * 3: Rollaway 경고
  */
#define LCD_WARN_NONE       0
#define LCD_WARN_LV1        1
#define LCD_WARN_LV2        2
#define LCD_WARN_ROLLAWAY   3
#define LCD_BRK_D           4
#define LCD_BRK_R           5
#define LCD_BRK_ROLLAWAY    6
  /* brake_type (2bit)
   * 0: 제동 없음
   * 1: D단 제동
   * 2: R단 제동
   * 3: Rollaway 제동
   */
#define LCD_BRK_NONE        0
#define LCD_BRK             1

   /* gear_state (2bit)
    * 0: P
    * 1: R
    * 2: N
    * 3: D
    */
#define LCD_GEAR_P          0
#define LCD_GEAR_R          1
#define LCD_GEAR_N          2
#define LCD_GEAR_D          3

    /* door_state (1bit)
     * 0: 닫힘
     * 1: 열림
     */
#define LCD_DOOR_CLOSE      0
#define LCD_DOOR_OPEN       1

     /* driver_present (1bit)
      * 0: 운전자 부재
      * 1: 운전자 존재
      */
#define LCD_DRIVER_ABSENT   0
#define LCD_DRIVER_PRESENT  1

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/
 
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

      /* --------------------------------
       * 32글자 LCD 문자열 생성 함수
       *
       * out_lcd1, out_lcd2는 각각 최소 33바이트 필요
       * -------------------------------- */
void lcd_make_strings(uint8 warning, uint8 brake, uint8 gear,
    uint8 door, uint8 driver, uint8 speed, uint8 notice,
    char out_lcd1[33], char out_lcd2[33]);

#endif /* LCD_H_ */
