/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxStm.h"

#include "IfxPort.h"
#include "IfxPort_PinMap.h"

#include "IfxMultican_Can.h"


IfxMultican_Can mcan;
IfxMultican_Can_Node canNode0, canNode1;

IfxMultican_Can_MsgObj txMsgObj;
IfxMultican_Can_MsgObj rxMsgObj;

IfxCpu_syncEvent cpuSyncEvent = 0;

void init_can_loopback(void);
void init_can(void);

void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);

    //확인용 led
    IfxPort_setPinModeOutput(IfxPort_P10_2.port, IfxPort_P10_2.pinIndex,
                                     IfxPort_OutputMode_pushPull,
                                     IfxPort_OutputIdx_general);
    IfxPort_setPinHigh(IfxPort_P10_2.port, IfxPort_P10_2.pinIndex);
        
    //루프백 테스트 시 init_can_loopback(); 사용
    init_can();

    IfxMultican_Message txmsg = { 0x123, IfxMultican_DataLengthCode_8, {0x11, 0x22}, FALSE};
    IfxMultican_Message rxmsg;

    uint8 tmp = 1;
    while(1)
    {
        IfxMultican_Can_MsgObj_sendMessage(&txMsgObj, &txmsg);
        while(!IfxMultican_Can_MsgObj_isTxPending(&txMsgObj));
        //while(!IfxMultican_Can_MsgObj_isRxPending(&rxMsgObj));
        //IfxMultican_Can_MsgObj_readMessage(&rxMsgObj, &rxmsg);
        IfxStm_wait(500);
        //IfxMultican_Can_MsgObj_clearRxPending(&rxMsgObj);
        IfxMultican_Can_MsgObj_clearTxPending(&txMsgObj);

        //확인용 led
        if(tmp)
            IfxPort_setPinLow(IfxPort_P10_2.port, IfxPort_P10_2.pinIndex);
        else
            IfxPort_setPinHigh(IfxPort_P10_2.port, IfxPort_P10_2.pinIndex);
        tmp = 1 - tmp;
    }
}

void init_can_loopback(void)
{
    // 1. 모듈 초기화
    IfxMultican_Can_Config canConfig;
    IfxMultican_Can_initModuleConfig(&canConfig, &MODULE_CAN); // 기본값 할당
    IfxMultican_Can_initModule(&mcan, &canConfig);             // 하드웨어 적용

    // 2. 노드 초기화
    IfxMultican_Can_NodeConfig canNodeConfig;
    IfxMultican_Can_Node_initConfig(&canNodeConfig, &mcan);
    canNodeConfig.nodeId = IfxMultican_NodeId_0;
    canNodeConfig.baudrate = 500000; // 500kbps 속도 설정

    //canNodeConfig.rxPin = &IfxMultican_RXD0A_P02_1_IN;
    //canNodeConfig.txPin = &IfxMultican_TXD0_P02_0_OUT;
    canNodeConfig.loopBackMode = TRUE;
    IfxMultican_Can_Node_init(&canNode0, &canNodeConfig);

    IfxMultican_Can_Node_initConfig(&canNodeConfig, &mcan);
    canNodeConfig.nodeId = IfxMultican_NodeId_1;
    canNodeConfig.baudrate = 500000; // 500kbps 속도 설정

    //canNodeConfig.rxPin = &IfxMultican_RXD0A_P02_1_IN;
    //canNodeConfig.txPin = &IfxMultican_TXD0_P02_0_OUT;
    canNodeConfig.loopBackMode = TRUE;
    IfxMultican_Can_Node_init(&canNode1, &canNodeConfig);

    IfxMultican_Can_MsgObjConfig canMsgObjConfig;
    IfxMultican_Can_MsgObj_initConfig(&canMsgObjConfig, &canNode0);

    canMsgObjConfig.msgObjId = 0; // 송신용으로 할당할 MO 번호 (예: 0번)
    canMsgObjConfig.messageId = 0x123; // 전송할 타겟 CAN ID
    canMsgObjConfig.frame = IfxMultican_Frame_transmit; // 프레임 방향을 송신으로 설정
    canMsgObjConfig.control.messageLen = IfxMultican_DataLengthCode_8; // DLC를 8바이트로 설정

    // 송신 MO 하드웨어 적용
    IfxMultican_Can_MsgObj_init(&txMsgObj, &canMsgObjConfig);

    IfxMultican_Can_MsgObj_initConfig(&canMsgObjConfig, &canNode1);

    canMsgObjConfig.msgObjId = 1;          // 사용할 MO 번호
    canMsgObjConfig.messageId = 0x123;      // 타겟 ID
    canMsgObjConfig.acceptanceMask = 0x7FF; // 11비트 완벽 일치 마스크
    canMsgObjConfig.frame = IfxMultican_Frame_receive; // 수신 모드

    // 수신 MO 하드웨어 적용
    IfxMultican_Can_MsgObj_init(&rxMsgObj, &canMsgObjConfig);
}

void init_can(void)
{
    // 1. 모듈 초기화
    IfxMultican_Can_Config canConfig;
    IfxMultican_Can_initModuleConfig(&canConfig, &MODULE_CAN); // 기본값 할당
    IfxMultican_Can_initModule(&mcan, &canConfig);             // 하드웨어 적용

    // 2. 노드 초기화
    IfxMultican_Can_NodeConfig canNodeConfig;
    IfxMultican_Can_Node_initConfig(&canNodeConfig, &mcan);
    canNodeConfig.nodeId = IfxMultican_NodeId_0;
    canNodeConfig.baudrate = 500000; // 500kbps 속도 설정

    //사용할 핀 각자에 맞춰서 포팅
    canNodeConfig.rxPin = &IfxMultican_RXD0B_P20_7_IN;
    canNodeConfig.txPin = &IfxMultican_TXD0_P20_8_OUT;
    IfxMultican_Can_Node_init(&canNode0, &canNodeConfig);

    IfxMultican_Can_MsgObjConfig canMsgObjConfig;
    IfxMultican_Can_MsgObj_initConfig(&canMsgObjConfig, &canNode0);

    canMsgObjConfig.msgObjId = 0; // 송신용으로 할당할 MO 번호 (예: 0번)
    canMsgObjConfig.messageId = 0x123; // 전송할 타겟 CAN ID
    canMsgObjConfig.frame = IfxMultican_Frame_transmit; // 프레임 방향을 송신으로 설정
    canMsgObjConfig.control.messageLen = IfxMultican_DataLengthCode_8; // DLC를 8바이트로 설정

    // 송신 MO 하드웨어 적용
    IfxMultican_Can_MsgObj_init(&txMsgObj, &canMsgObjConfig);

    IfxMultican_Can_MsgObj_initConfig(&canMsgObjConfig, &canNode0);

    canMsgObjConfig.msgObjId = 1;          // 사용할 MO 번호
    canMsgObjConfig.messageId = 0x123;      // 타겟 ID
    canMsgObjConfig.acceptanceMask = 0x7FF; // 11비트 완벽 일치 마스크
    canMsgObjConfig.frame = IfxMultican_Frame_receive; // 수신 모드

    // 수신 MO 하드웨어 적용
    IfxMultican_Can_MsgObj_init(&rxMsgObj, &canMsgObjConfig);
}
